// post requests
const loginEndPoint = "login";
const registerEndPoint = "client_register"; // missing some properites
const showCitiesEndPoint = "cities/"; // missing some properites
const forgetPasswordEndPoint = "resend_code"; // not founded
const confirmCodeEndPoint = "verify"; // make confirm and active together
const changePasswordEndPoint = "reset_password";
const logoutEndPoint = "logout";
const checkCodeEndPoint = "check_code";
const contactWithUsEndPoint = "contact";
const suggestionsEndPoint = "contact";
const updatePersonalInfoEndPoint = "client/profile";
const showSectionProductsEndPoint = "categories/";
const editPasswordEndPoint = "edit_password";
const forgetPasswordEndPoint2 = 'forget_password';
// get requests
const homeSliderEndPoint = "sliders";
const homeCategoriesEndPoint = "categories";
const homeProductsEndPoint = "products";
const homeSearchForProductEndPoint = "search";
const productDetailsEndPoint = "products/";
const getRatesEndPoint = "products/";
const favoritesEndPoint = "client/products/favorites";
const cartEndPoint = "client/cart";
const deleteItemFromCartEndPoint = "client/cart/delete_item/";
const updateItemAmountEndPoint = "client/cart/";
const favProductEndPoint = "client/products/";
const addToCartEndPoint = "client/cart";
const myOrdersEndPoint = "client/orders";
const notificationsEndPoint = "notifications";
const orderDetailsEndPoint = "client/orders/";
const aboutAppEndPoint = "about";
const knownQuestionsEndPoint = "faqs";
const privacyEndPoint = "policy";
const conditionsEndPoint = "terms";
const showOurPlaceLocationEndPoint = "contact";
const addAddressEndPoint = "client/addresses";
const addressesEndPoint = "client/addresses";
const deleteAddressEndPoint = "client/addresses/";
